[package]
name = "spritecutout"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
image = "0.24"
walkdir = "2"
os_str_bytes = { version = "6", features = ["raw_os_str", "memchr"] }
clap = { version = "4", features = ["derive"] }